In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time

In [6]:
url = "https://volcano.si.edu/reports_weekly.cfm?vtab=feeds"

response = requests.get(url)
response

In [7]:
soup = BeautifulSoup(response.content)
table = soup.find('table')
table

<table>
<thead>
<tr>
<th colspan="5">Smithsonian / USGS Weekly Volcanic Activity Report for the week of 19 March-25 March 2025</th>
</tr>
<tr>
<th>Name</th>
<th>Country</th>
<th>Volcanic Region</th>
<th>Eruption Start Date</th>
<th class="aligncenter">Report Status</th>
</tr>
</thead>
<tbody>
<tr>
<td class="textbold"><a href="#vn_264180">Lewotobi</a></td>
<td class="textbold">Indonesia</td>
<td class="textbold">Sunda Volcanic Arc</td>
<td class="textbold">2023 Dec 23</td>
<td class="textbold aligncenter"><a data-tooltip="tt264180" style="color:red;">New</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_264230">Lewotolok</a></td>
<td class="textbold">Indonesia</td>
<td class="textbold">Sunda Volcanic Arc</td>
<td class="textbold">2025 Jan 16</td>
<td class="textbold aligncenter"><a data-tooltip="tt264230" style="color:red;">New</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_345040">Poas</a></td>
<td class="textbold">Costa Rica</td>
<td class="textbold">Central America Volcanic Arc</td>
<td class="textbold">2025 Jan 5</td>
<td class="textbold aligncenter"><a data-tooltip="tt345040" style="color:red;">New</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_284141">Ahyi</a></td>
<td class="textbold">United States</td>
<td class="textbold">Mariana Volcanic Arc</td>
<td class="textbold">2024 Aug 5</td>
<td class="textbold aligncenter"><a data-tooltip="tt284141" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_282080">Aira</a></td>
<td class="textbold">Japan</td>
<td class="textbold">Ryukyu Volcanic Arc</td>
<td class="textbold">2017 Mar 25</td>
<td class="textbold aligncenter"><a data-tooltip="tt282080" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_300250">Bezymianny</a></td>
<td class="textbold">Russia</td>
<td class="textbold">Eastern Kamchatka Volcanic Arc</td>
<td class="textbold">2024 Dec 24</td>
<td class="textbold aligncenter"><a data-tooltip="tt300250" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_268010">Dukono</a></td>
<td class="textbold">Indonesia</td>
<td class="textbold">Halmahera Volcanic Arc</td>
<td class="textbold">1933 Aug 13</td>
<td class="textbold aligncenter"><a data-tooltip="tt268010" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_211060">Etna</a></td>
<td class="textbold">Italy</td>
<td class="textbold">Sicily Volcanic Province</td>
<td class="textbold">2022 Nov 27</td>
<td class="textbold aligncenter"><a data-tooltip="tt211060" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_311120">Great Sitkin</a></td>
<td class="textbold">United States</td>
<td class="textbold">Aleutian Ridge Volcanic Arc</td>
<td class="textbold">2021 May 25</td>
<td class="textbold aligncenter"><a data-tooltip="tt311120" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_243080">Home Reef</a></td>
<td class="textbold">Tonga</td>
<td class="textbold">Tofua Volcanic Arc</td>
<td class="textbold">2024 Dec 4</td>
<td class="textbold aligncenter"><a data-tooltip="tt243080" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_268030">Ibu</a></td>
<td class="textbold">Indonesia</td>
<td class="textbold">Halmahera Volcanic Arc</td>
<td class="textbold">2008 Apr 5</td>
<td class="textbold aligncenter"><a data-tooltip="tt268030" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_272020">Kanlaon</a></td>
<td class="textbold">Philippines</td>
<td class="textbold">Negros-Sulu Volcanic Arc</td>
<td class="textbold">2024 Oct 19</td>
<td class="textbold aligncenter"><a data-tooltip="tt272020" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_300130">Karymsky</a></td>
<td class="textbold">Russia</td>
<td class="textbold">Eastern Kamchatka Volcanic Arc</td>
<td class="textbold">—</td>
<td class="textbold aligncenter"><a data-tooltip="tt300130" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_332010">Kilauea</a></td>
<td class="textbold">United States</td>
<td class="textbold">Hawaiian-Emperor Hotspot Volcano Group</td>
<td class="textbold">2024 Dec 23</td>
<td class="textbold aligncenter"><a data-tooltip="tt332010" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_261140">Marapi</a></td>
<td class="textbold">Indonesia</td>
<td class="textbold">Sunda Volcanic Arc</td>
<td class="textbold">2023 Dec 3</td>
<td class="textbold aligncenter"><a data-tooltip="tt261140" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_263250">Merapi</a></td>
<td class="textbold">Indonesia</td>
<td class="textbold">Sunda Volcanic Arc</td>
<td class="textbold">2020 Dec 31</td>
<td class="textbold aligncenter"><a data-tooltip="tt263250" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_223020">Nyamulagira</a></td>
<td class="textbold">DR Congo</td>
<td class="textbold">Albertine Rift Volcanic Province</td>
<td class="textbold">2018 Apr 14</td>
<td class="textbold aligncenter"><a data-tooltip="tt223020" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_341090">Popocatepetl</a></td>
<td class="textbold">Mexico</td>
<td class="textbold">Trans-Mexican Volcanic Arc</td>
<td class="textbold">2005 Jan 9</td>
<td class="textbold aligncenter"><a data-tooltip="tt341090" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_345020">Rincon de la Vieja</a></td>
<td class="textbold">Costa Rica</td>
<td class="textbold">Central America Volcanic Arc</td>
<td class="textbold">—</td>
<td class="textbold aligncenter"><a data-tooltip="tt345020" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_263300">Semeru</a></td>
<td class="textbold">Indonesia</td>
<td class="textbold">Sunda Volcanic Arc</td>
<td class="textbold">2017 Jun 6</td>
<td class="textbold aligncenter"><a data-tooltip="tt263300" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_300270">Sheveluch</a></td>
<td class="textbold">Russia</td>
<td class="textbold">Eastern Kamchatka Volcanic Arc</td>
<td class="textbold">1999 Aug 15</td>
<td class="textbold aligncenter"><a data-tooltip="tt300270" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_282030">Suwanosejima</a></td>
<td class="textbold">Japan</td>
<td class="textbold">Ryukyu Volcanic Arc</td>
<td class="textbold">2004 Oct 23</td>
<td class="textbold aligncenter"><a data-tooltip="tt282030" style="color:green;">Continuing</a></td>
</tr>
<tr>
<td class="textbold"><a href="#vn_241040">Whakaari/White Island</a></td>
<td class="textbold">New Zealand</td>
<td class="textbold">Taupo Volcanic Arc</td>
<td class="textbold">2024 May 24</td>
<td class="textbold aligncenter"><a data-tooltip="tt241040" style="color:green;">Continuing</a></td>
</tr>
</tbody>
</table>

In [8]:
# Extract column names
headers = [th.get_text(strip=True) for th in table.find_all('th')][1:]
headers

['Name', 'Country', 'Volcanic Region', 'Eruption Start Date', 'Report Status']

In [9]:
volcano_data = []
headers = [th.get_text(strip=True) for th in table.find_all('th')][1:]

for row in table.find_all('tr')[2:]:  # Skip header row
    cols = row.find_all(['td', 'th'])

    print(f"Row columns count: {len(cols)}")
    print(f"Row columns text: {[col.get_text(strip=True) for col in cols]}")
    
    if len(cols) < len(headers):
        print("Skipping row: not enough columns")
        continue

    try:
        volcano_link = row.find('a', href=re.compile(r'#vn_'))
        
        if not volcano_link:
            print("No volcano link found in this row")
            continue
        
        volcano_id = volcano_link['href'].split('#vn_')[1]
        volcano_name = volcano_link.get_text(strip=True)
        start_date = cols[3].get_text(strip=True)
        
        report_status = row.find("a", attrs={"data-tooltip": True})
        report_text = report_status.get_text(strip=True) if report_status else None

        row_data = {
              'volcano_id': volcano_id,
              'volcano_name': volcano_name,
              'start_date': start_date,
              'report_status': report_text
        }
        
        # # Add other column data
        # for i, col in enumerate(cols):
        #     if i < len(headers):
        #         row_data[headers[i]] = col.get_text(strip=True)
        
        volcano_data.append(row_data)
        print(f"Added data for: {volcano_name}")
    
    except Exception as e:
        print(f"Error processing row: {e}")

df = pd.DataFrame(volcano_data)
df

Row columns count: 5
Row columns text: ['Lewotobi', 'Indonesia', 'Sunda Volcanic Arc', '2023 Dec 23', 'New']
Added data for: Lewotobi
Row columns count: 5
Row columns text: ['Lewotolok', 'Indonesia', 'Sunda Volcanic Arc', '2025 Jan 16', 'New']
Added data for: Lewotolok
Row columns count: 5
Row columns text: ['Poas', 'Costa Rica', 'Central America Volcanic Arc', '2025 Jan 5', 'New']
Added data for: Poas
Row columns count: 5
Row columns text: ['Ahyi', 'United States', 'Mariana Volcanic Arc', '2024 Aug 5', 'Continuing']
Added data for: Ahyi
Row columns count: 5
Row columns text: ['Aira', 'Japan', 'Ryukyu Volcanic Arc', '2017 Mar 25', 'Continuing']
Added data for: Aira
Row columns count: 5
Row columns text: ['Bezymianny', 'Russia', 'Eastern Kamchatka Volcanic Arc', '2024 Dec 24', 'Continuing']
Added data for: Bezymianny
Row columns count: 5
Row columns text: ['Dukono', 'Indonesia', 'Halmahera Volcanic Arc', '1933 Aug 13', 'Continuing']
Added data for: Dukono
Row columns count: 5
Row columns text: ['Etna', 'Italy', 'Sicily Volcanic Province', '2022 Nov 27', 'Continuing']
Added data for: Etna
Row columns count: 5
Row columns text: ['Great Sitkin', 'United States', 'Aleutian Ridge Volcanic Arc', '2021 May 25', 'Continuing']
Added data for: Great Sitkin
Row columns count: 5
Row columns text: ['Home Reef', 'Tonga', 'Tofua Volcanic Arc', '2024 Dec 4', 'Continuing']
Added data for: Home Reef
Row columns count: 5
Row columns text: ['Ibu', 'Indonesia', 'Halmahera Volcanic Arc', '2008 Apr 5', 'Continuing']
Added data for: Ibu
Row columns count: 5
Row columns text: ['Kanlaon', 'Philippines', 'Negros-Sulu Volcanic Arc', '2024 Oct 19', 'Continuing']
Added data for: Kanlaon
Row columns count: 5
Row columns text: ['Karymsky', 'Russia', 'Eastern Kamchatka Volcanic Arc', '—', 'Continuing']
Added data for: Karymsky
Row columns count: 5
Row columns text: ['Kilauea', 'United States', 'Hawaiian-Emperor Hotspot Volcano Group', '2024 Dec 23', 'Continuing']
Added data for: Kilauea
Row columns count: 5
Row columns text: ['Marapi', 'Indonesia', 'Sunda Volcanic Arc', '2023 Dec 3', 'Continuing']
Added data for: Marapi
Row columns count: 5
Row columns text: ['Merapi', 'Indonesia', 'Sunda Volcanic Arc', '2020 Dec 31', 'Continuing']
Added data for: Merapi
Row columns count: 5
Row columns text: ['Nyamulagira', 'DR Congo', 'Albertine Rift Volcanic Province', '2018 Apr 14', 'Continuing']
Added data for: Nyamulagira
Row columns count: 5
Row columns text: ['Popocatepetl', 'Mexico', 'Trans-Mexican Volcanic Arc', '2005 Jan 9', 'Continuing']
Added data for: Popocatepetl
Row columns count: 5
Row columns text: ['Rincon de la Vieja', 'Costa Rica', 'Central America Volcanic Arc', '—', 'Continuing']
Added data for: Rincon de la Vieja
Row columns count: 5
Row columns text: ['Semeru', 'Indonesia', 'Sunda Volcanic Arc', '2017 Jun 6', 'Continuing']
Added data for: Semeru
Row columns count: 5
Row columns text: ['Sheveluch', 'Russia', 'Eastern Kamchatka Volcanic Arc', '1999 Aug 15', 'Continuing']
Added data for: Sheveluch
Row columns count: 5
Row columns text: ['Suwanosejima', 'Japan', 'Ryukyu Volcanic Arc', '2004 Oct 23', 'Continuing']
Added data for: Suwanosejima
Row columns count: 5
Row columns text: ['Whakaari/White Island', 'New Zealand', 'Taupo Volcanic Arc', '2024 May 24', 'Continuing']
Added data for: Whakaari/White Island

   volcano_id           volcano_name   start_date report_status
0      264180               Lewotobi  2023 Dec 23           New
1      264230              Lewotolok  2025 Jan 16           New
2      345040                   Poas   2025 Jan 5           New
3      284141                   Ahyi   2024 Aug 5    Continuing
4      282080                   Aira  2017 Mar 25    Continuing
5      300250             Bezymianny  2024 Dec 24    Continuing
6      268010                 Dukono  1933 Aug 13    Continuing
7      211060                   Etna  2022 Nov 27    Continuing
8      311120           Great Sitkin  2021 May 25    Continuing
9      243080              Home Reef   2024 Dec 4    Continuing
10     268030                    Ibu   2008 Apr 5    Continuing
11     272020                Kanlaon  2024 Oct 19    Continuing
12     300130               Karymsky            —    Continuing
13     332010                Kilauea  2024 Dec 23    Continuing
14     261140                 Marapi   2023 Dec 3    Continuing
15     263250                 Merapi  2020 Dec 31    Continuing
16     223020            Nyamulagira  2018 Apr 14    Continuing
17     341090           Popocatepetl   2005 Jan 9    Continuing
18     345020     Rincon de la Vieja            —    Continuing
19     263300                 Semeru   2017 Jun 6    Continuing
20     300270              Sheveluch  1999 Aug 15    Continuing
21     282030           Suwanosejima  2004 Oct 23    Continuing
22     241040  Whakaari/White Island  2024 May 24    Continuing

In [10]:
def scrap_volcanic_weekly_report():

    url = "https://volcano.si.edu/reports_weekly.cfm?vtab=feeds"
    response = requests.get(url)

    soup = BeautifulSoup(response.content)
    table = soup.find('table')

    volcano_data = []
    headers = [th.get_text(strip=True) for th in table.find_all('th')][1:]

    for row in table.find_all('tr')[2:]:  # Skip header row
        cols = row.find_all(['td', 'th'])

        if len(cols) < len(headers):
            print("Skipping row: not enough columns")
            continue

        try:
            volcano_link = row.find('a', href=re.compile(r'#vn_'))
            
            if not volcano_link:
                print("No volcano link found in this row")
                continue
            
            volcano_id = volcano_link['href'].split('#vn_')[1]
            volcano_name = volcano_link.get_text(strip=True)
            start_date = cols[3].get_text(strip=True)
            
            report_status = row.find("a", attrs={"data-tooltip": True})
            report_text = report_status.get_text(strip=True) if report_status else None

            row_data = {
                'volcano_id': volcano_id,
                'volcano_name': volcano_name,
                'start_date': start_date,
                'report_status': report_text
            }
            
            volcano_data.append(row_data)
        
        except Exception as e:
            print(f"Error processing row: {e}")

    volcanic_weekly_report = pd.DataFrame(volcano_data)

    return volcanic_weekly_report
    
volcanic_weekly_report = scrap_volcanic_weekly_report()
volcanic_weekly_report

   volcano_id           volcano_name   start_date report_status
0      264180               Lewotobi  2023 Dec 23           New
1      264230              Lewotolok  2025 Jan 16           New
2      345040                   Poas   2025 Jan 5           New
3      284141                   Ahyi   2024 Aug 5    Continuing
4      282080                   Aira  2017 Mar 25    Continuing
5      300250             Bezymianny  2024 Dec 24    Continuing
6      268010                 Dukono  1933 Aug 13    Continuing
7      211060                   Etna  2022 Nov 27    Continuing
8      311120           Great Sitkin  2021 May 25    Continuing
9      243080              Home Reef   2024 Dec 4    Continuing
10     268030                    Ibu   2008 Apr 5    Continuing
11     272020                Kanlaon  2024 Oct 19    Continuing
12     300130               Karymsky            —    Continuing
13     332010                Kilauea  2024 Dec 23    Continuing
14     261140                 Marapi   2023 Dec 3    Continuing
15     263250                 Merapi  2020 Dec 31    Continuing
16     223020            Nyamulagira  2018 Apr 14    Continuing
17     341090           Popocatepetl   2005 Jan 9    Continuing
18     345020     Rincon de la Vieja            —    Continuing
19     263300                 Semeru   2017 Jun 6    Continuing
20     300270              Sheveluch  1999 Aug 15    Continuing
21     282030           Suwanosejima  2004 Oct 23    Continuing
22     241040  Whakaari/White Island  2024 May 24    Continuing

In [ ]:
volcano_link = row.find('a', href=re.compile(r'#vn_'))
volcano_link

In [ ]:
row.find('a', href=re.compile(r'#vn_'))

In [ ]:
volcano_number = volcano_link['href'].split('#vn_')[1]
volcano_number

'241040'

In [ ]:
volcano_name = volcano_link.get_text(strip=True)
volcano_name

'Whakaari/White Island'

In [ ]:
start_date = cols[3].get_text(strip=True)
start_date

'2024 May 24'

In [ ]:
report_status = row.find("a", attrs={"data-tooltip": True})
report_status

In [ ]:
report_text = report_status.get_text(strip=True) if report_status else None
report_text

'Continuing'

In [ ]:
volcano_data

[{'volcano_id': '264180',
  'volcano_name': 'Lewotobi',
  'start_date': '2023 Dec 23',
  'report_status': 'New'},
 {'volcano_id': '264230',
  'volcano_name': 'Lewotolok',
  'start_date': '2025 Jan 16',
  'report_status': 'New'},
 {'volcano_id': '345040',
  'volcano_name': 'Poas',
  'start_date': '2025 Jan 5',
  'report_status': 'New'},
 {'volcano_id': '284141',
  'volcano_name': 'Ahyi',
  'start_date': '2024 Aug 5',
  'report_status': 'Continuing'},
 {'volcano_id': '282080',
  'volcano_name': 'Aira',
  'start_date': '2017 Mar 25',
  'report_status': 'Continuing'},
 {'volcano_id': '300250',
  'volcano_name': 'Bezymianny',
  'start_date': '2024 Dec 24',
  'report_status': 'Continuing'},
 {'volcano_id': '268010',
  'volcano_name': 'Dukono',
  'start_date': '1933 Aug 13',
  'report_status': 'Continuing'},
 {'volcano_id': '211060',
  'volcano_name': 'Etna',
  'start_date': '2022 Nov 27',
  'report_status': 'Continuing'},
 {'volcano_id': '311120',
  'volcano_name': 'Great Sitkin',
  'start_date': '2021 May 25',
  'report_status': 'Continuing'},
 {'volcano_id': '243080',
  'volcano_name': 'Home Reef',
  'start_date': '2024 Dec 4',
  'report_status': 'Continuing'},
 {'volcano_id': '268030',
  'volcano_name': 'Ibu',
  'start_date': '2008 Apr 5',
  'report_status': 'Continuing'},
 {'volcano_id': '272020',
  'volcano_name': 'Kanlaon',
  'start_date': '2024 Oct 19',
  'report_status': 'Continuing'},
 {'volcano_id': '300130',
  'volcano_name': 'Karymsky',
  'start_date': '—',
  'report_status': 'Continuing'},
 {'volcano_id': '332010',
  'volcano_name': 'Kilauea',
  'start_date': '2024 Dec 23',
  'report_status': 'Continuing'},
 {'volcano_id': '261140',
  'volcano_name': 'Marapi',
  'start_date': '2023 Dec 3',
  'report_status': 'Continuing'},
 {'volcano_id': '263250',
  'volcano_name': 'Merapi',
  'start_date': '2020 Dec 31',
  'report_status': 'Continuing'},
 {'volcano_id': '223020',
  'volcano_name': 'Nyamulagira',
  'start_date': '2018 Apr 14',
  'report_status': 'Continuing'},
 {'volcano_id': '341090',
  'volcano_name': 'Popocatepetl',
  'start_date': '2005 Jan 9',
  'report_status': 'Continuing'},
 {'volcano_id': '345020',
  'volcano_name': 'Rincon de la Vieja',
  'start_date': '—',
  'report_status': 'Continuing'},
 {'volcano_id': '263300',
  'volcano_name': 'Semeru',
  'start_date': '2017 Jun 6',
  'report_status': 'Continuing'},
 {'volcano_id': '300270',
  'volcano_name': 'Sheveluch',
  'start_date': '1999 Aug 15',
  'report_status': 'Continuing'},
 {'volcano_id': '282030',
  'volcano_name': 'Suwanosejima',
  'start_date': '2004 Oct 23',
  'report_status': 'Continuing'},
 {'volcano_id': '241040',
  'volcano_name': 'Whakaari/White Island',
  'start_date': '2024 May 24',
  'report_status': 'Continuing'}]

#### Scraping Yearly Report 2025

In [11]:
url = "https://volcano.si.edu/faq/index.cfm?question=eruptionsbyyear&checkyear=2025"
response = requests.get(url)

In [12]:
soup = BeautifulSoup(response.content)
table = soup.find('table')
table

<table>
<thead>
<tr>
<th>Volcano</th>
<th>Country</th>
<th>Eruption Start Date</th>
<th>Eruption Stop Date</th>
<th>Max VEI</th>
</tr>
</thead>
<tbody>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=351060">Purace</a></td>
<td>Colombia</td>
<td>2025 Jan 19</td>
<td>2025 Feb 21</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=264230">Lewotolok</a></td>
<td>Indonesia</td>
<td>2025 Jan 16</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=344040">Telica</a></td>
<td>Nicaragua</td>
<td>2025 Jan 11</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=345040">Poas</a></td>
<td>Costa Rica</td>
<td>2025 Jan 5</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=300250">Bezymianny</a></td>
<td>Russia</td>
<td>2024 Dec 24</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=332010">Kilauea</a></td>
<td>United States</td>
<td>2024 Dec 23</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=263200">Dieng Volcanic Complex</a></td>
<td>Indonesia</td>
<td>2024 Dec 18</td>
<td>2025 Jan 6</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=243080">Home Reef</a></td>
<td>Tonga</td>
<td>2024 Dec 4</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=261230">Dempo</a></td>
<td>Indonesia</td>
<td>2024 Nov 23</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=272020">Kanlaon</a></td>
<td>Philippines</td>
<td>2024 Oct 19</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=284141">Ahyi</a></td>
<td>United States</td>
<td>2024 Aug 5</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=241040">Whakaari/White Island</a></td>
<td>New Zealand</td>
<td>2024 May 24</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=273070">Taal</a></td>
<td>Philippines</td>
<td>2024 Apr 12</td>
<td>2025 Feb 21 (continuing)</td>
<td>–</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=264180">Lewotobi</a></td>
<td>Indonesia</td>
<td>2023 Dec 23</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=261140">Marapi</a></td>
<td>Indonesia</td>
<td>2023 Dec 3</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=211060">Etna</a></td>
<td>Italy</td>
<td>2022 Nov 27</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=311120">Great Sitkin</a></td>
<td>United States</td>
<td>2021 May 25</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=263250">Merapi</a></td>
<td>Indonesia</td>
<td>2020 Dec 31</td>
<td>2025 Feb 21 (continuing)</td>
<td>1</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=352090">Sangay</a></td>
<td>Ecuador</td>
<td>2019 Mar 26</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=251020">Manam</a></td>
<td>Papua New Guinea</td>
<td>2018 May 10 ± 10 days</td>
<td>2025 Feb 21 (continuing)</td>
<td>4</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=223020">Nyamulagira</a></td>
<td>DR Congo</td>
<td>2018 Apr 14</td>
<td>2025 Feb 21 (continuing)</td>
<td>0</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=263300">Semeru</a></td>
<td>Indonesia</td>
<td>2017 Jun 6</td>
<td>2025 Feb 21 (continuing)</td>
<td>4</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=222120">Ol Doinyo Lengai</a></td>
<td>Tanzania</td>
<td>2017 Apr 9</td>
<td>2025 Feb 6 (continuing)</td>
<td>0</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=282080">Aira</a></td>
<td>Japan</td>
<td>2017 Mar 25</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=354006">Sabancaya</a></td>
<td>Peru</td>
<td>2016 Nov 6</td>
<td>2025 Feb 21 (continuing)</td>
<td>3</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=252010">Langila</a></td>
<td>Papua New Guinea</td>
<td>2015 Oct 22 (?)</td>
<td>2025 Feb 1 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=344100">Masaya</a></td>
<td>Nicaragua</td>
<td>2015 Oct 3</td>
<td>2025 Feb 6 (continuing)</td>
<td>1</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=243060">Tofua</a></td>
<td>Tonga</td>
<td>2015 Oct 2</td>
<td>2025 Feb 20 (continuing)</td>
<td>0</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=357120">Villarrica</a></td>
<td>Chile</td>
<td>2014 Dec 2 ± 7 days</td>
<td>2025 Feb 21 (continuing)</td>
<td>3</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=351020">Nevado del Ruiz</a></td>
<td>Colombia</td>
<td>2014 Nov 18</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=390090">Saunders</a></td>
<td>United Kingdom</td>
<td>2014 Nov 12</td>
<td>2025 Jan 16 (continuing)</td>
<td>1</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=234010">Heard</a></td>
<td>Australia</td>
<td>2012 Sep 5 ± 4 days</td>
<td>2025 Feb 13 (continuing)</td>
<td>0</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=352010">Reventador</a></td>
<td>Ecuador</td>
<td>2008 Jul 27</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=268030">Ibu</a></td>
<td>Indonesia</td>
<td>2008 Apr 5</td>
<td>2025 Feb 21 (continuing)</td>
<td>1</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=341090">Popocatepetl</a></td>
<td>Mexico</td>
<td>2005 Jan 9</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=282030">Suwanosejima</a></td>
<td>Japan</td>
<td>2004 Oct 23</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=223030">Nyiragongo</a></td>
<td>DR Congo</td>
<td>2002 May 17 (?)</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=342090">Fuego</a></td>
<td>Guatemala</td>
<td>2002 Jan 4</td>
<td>2025 Feb 21 (continuing)</td>
<td>3</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=255020">Bagana</a></td>
<td>Papua New Guinea</td>
<td>2000 Feb 28 (in or before)</td>
<td>2025 Jan 31 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=300270">Sheveluch</a></td>
<td>Russia</td>
<td>1999 Aug 15</td>
<td>2025 Feb 21 (continuing)</td>
<td>4</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=390020">Erebus</a></td>
<td>Antarctica</td>
<td>1972 Dec 16 (in or before) ± 15 days</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=221080">Erta Ale</a></td>
<td>Ethiopia</td>
<td>1967 Jul 2 (in or before) ± 182 days</td>
<td>2025 Feb 21 (continuing)</td>
<td>0</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=211040">Stromboli</a></td>
<td>Italy</td>
<td>1934 Feb 2</td>
<td>2025 Feb 21 (continuing)</td>
<td>2</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=268010">Dukono</a></td>
<td>Indonesia</td>
<td>1933 Aug 13</td>
<td>2025 Feb 21 (continuing)</td>
<td>3</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=342030">Santa Maria</a></td>
<td>Guatemala</td>
<td>1922 Jun 22</td>
<td>2025 Feb 21 (continuing)</td>
<td>3</td>
</tr>
<tr>
<td class="textbold"><a href="/volcano.cfm?vn=257100">Yasur</a></td>
<td>Vanuatu</td>
<td>1270 ± 110 years</td>
<td>2025 Feb 21 (continuing)</td>
<td>3</td>
</tr>
</tbody>
</table>

In [13]:
# Extract column names
headers = [th.get_text(strip=True) for th in table.find_all('th')]
headers

['Volcano', 'Country', 'Eruption Start Date', 'Eruption Stop Date', 'Max VEI']

In [69]:
soup = BeautifulSoup(response.text, 'html.parser')

# Find the table - you might need to adjust the selector based on the actual page structure
table = soup.find('table')

# Extract table data
data = []

# Get table headers
headers = []
for th in table.find_all('th'):
    headers.append(th.text.strip())

# Get table rows
for row in table.find_all('tr')[1:]:  # Skip the header row
    row_data = []
    for td in row.find_all('td'):
        row_data.append(td.text.strip())
    
    if row_data:  # Skip empty rows
        data.append(row_data)

# Create a DataFrame
df = pd.DataFrame(data, columns=headers)
df

,Volcano,Country,Eruption Start Date,Eruption Stop Date,Max VEI
0,Purace,Colombia,2025 Jan 19,2025 Feb 21,–
1,Lewotolok,Indonesia,2025 Jan 16,2025 Feb 21 (continuing),–
2,Telica,Nicaragua,2025 Jan 11,2025 Feb 21 (continuing),–
3,Poas,Costa Rica,2025 Jan 5,2025 Feb 21 (continuing),–
4,Bezymianny,Russia,2024 Dec 24,2025 Feb 21 (continuing),–
5,Kilauea,United States,2024 Dec 23,2025 Feb 21 (continuing),–
6,Dieng Volcanic Complex,Indonesia,2024 Dec 18,2025 Jan 6,–
7,Home Reef,Tonga,2024 Dec 4,2025 Feb 21 (continuing),–
8,Dempo,Indonesia,2024 Nov 23,2025 Feb 21 (continuing),–
9,Kanlaon,Philippines,2024 Oct 19,2025 Feb 21 (continuing),–
10,Ahyi,United States,2024 Aug 5,2025 Feb 21 (continuing),–
11,Whakaari/White Island,New Zealand,2024 May 24,2025 Feb 21 (continuing),–
12,Taal,Philippines,2024 Apr 12,2025 Feb 21 (continuing),–
13,Lewotobi,Indonesia,2023 Dec 23,2025 Feb 21 (continuing),2
14,Marapi,Indonesia,2023 Dec 3,2025 Feb 21 (continuing),2
15,Etna,Italy,2022 Nov 27,2025 Feb 21 (continuing),2
16,Great Sitkin,United States,2021 May 25,2025 Feb 21 (continuing),2
17,Merapi,Indonesia,2020 Dec 31,2025 Feb 21 (continuing),1
18,Sangay,Ecuador,2019 Mar 26,2025 Feb 21 (continuing),2
19,Manam,Papua New Guinea,2018 May 10 ± 10 days,2025 Feb 21 (continuing),4
20,Nyamulagira,DR Congo,2018 Apr 14,2025 Feb 21 (continuing),0
21,Semeru,Indonesia,2017 Jun 6,2025 Feb 21 (continuing),4
22,Ol Doinyo Lengai,Tanzania,2017 Apr 9,2025 Feb 6 (continuing),0
23,Aira,Japan,2017 Mar 25,2025 Feb 21 (continuing),2
24,Sabancaya,Peru,2016 Nov 6,2025 Feb 21 (continuing),3
25,Langila,Papua New Guinea,2015 Oct 22 (?),2025 Feb 1 (continuing),2
26,Masaya,Nicaragua,2015 Oct 3,2025 Feb 6 (continuing),1
27,Tofua,Tonga,2015 Oct 2,2025 Feb 20 (continuing),0
28,Villarrica,Chile,2014 Dec 2 ± 7 days,2025 Feb 21 (continuing),3
29,Nevado del Ruiz,Colombia,2014 Nov 18,2025 Feb 21 (continuing),2
30,Saunders,United Kingdom,2014 Nov 12,2025 Jan 16 (continuing),1
31,Heard,Australia,2012 Sep 5 ± 4 days,2025 Feb 13 (continuing),0
32,Reventador,Ecuador,2008 Jul 27,2025 Feb 21 (continuing),2
33,Ibu,Indonesia,2008 Apr 5,2025 Feb 21 (continuing),1
34,Popocatepetl,Mexico,2005 Jan 9,2025 Feb 21 (continuing),2
35,Suwanosejima,Japan,2004 Oct 23,2025 Feb 21 (continuing),2
36,Nyiragongo,DR Congo,2002 May 17 (?),2025 Feb 21 (continuing),2
37,Fuego,Guatemala,2002 Jan 4,2025 Feb 21 (continuing),3
38,Bagana,Papua New Guinea,2000 Feb 28 (in or before),2025 Jan 31 (continuing),2
39,Sheveluch,Russia,1999 Aug 15,2025 Feb 21 (continuing),4
40,Erebus,Antarctica,1972 Dec 16 (in or before) ± 15 days,2025 Feb 21 (continuing),2
41,Erta Ale,Ethiopia,1967 Jul 2 (in or before) ± 182 days,2025 Feb 21 (continuing),0
42,Stromboli,Italy,1934 Feb 2,2025 Feb 21 (continuing),2
43,Dukono,Indonesia,1933 Aug 13,2025 Feb 21 (continuing),3
44,Santa Maria,Guatemala,1922 Jun 22,2025 Feb 21 (continuing),3
45,Yasur,Vanuatu,1270 ± 110 years,2025 Feb 21 (continuing),3

In [82]:
def scrap_yearly_report():
    url = "https://volcano.si.edu/faq/index.cfm?question=eruptionsbyyear&checkyear=2025"
    response = requests.get(url)

    soup = BeautifulSoup(response.text, 'html.parser')

    # Find the table - you might need to adjust the selector based on the actual page structure
    table = soup.find('table')

    # Extract table data
    data = []

    # Get table headers
    headers = []
    for th in table.find_all('th'):
        headers.append(th.text.strip())

    # Get table rows
    for row in table.find_all('tr')[1:]:  # Skip the header row
        row_data = []
        for td in row.find_all('td'):
            row_data.append(td.text.strip())
        
        if row_data:  # Skip empty rows
            data.append(row_data)

    # Create a DataFrame
    yearly_report = pd.DataFrame(data, columns=headers)
    yearly_report.columns = [column.lower() for column in yearly_report.columns]
    return yearly_report

In [94]:
def clean_yearly_report():
    date_column = 'eruption stop date'
    
    df = scrap_yearly_report()
    # Create the status column with default 'Over'
    df['status'] = 'Over'
    
    # Update status based on the continuing text
    mask = df[date_column].str.contains('\(continuing\)', regex=True, na=False)
    df.loc[mask, 'status'] = 'On going'
    
    # Clean up the date strings
    df[date_column] = df[date_column].str.replace(r'\s*\(continuing\)\s*', '', regex=True)
    
    # Count and print how many ongoing eruptions were found
    ongoing_count = df['status'].value_counts().get('On going', 0)
    print(f"Found {ongoing_count} ongoing eruptions")

    df = df[['volcano', 'country', 'eruption start date', 'eruption stop date', 'status', 'max vei']]
    df.rename(columns={'volcano':'volcano_name'}, inplace=True)
    
    return df

<>:9: SyntaxWarning: invalid escape sequence '\('
<>:9: SyntaxWarning: invalid escape sequence '\('
/var/folders/yz/shh48k7s5kg3qtp0x9hzjb6c0000gn/T/ipykernel_77563/3504332965.py:9: SyntaxWarning: invalid escape sequence '\('
  mask = df[date_column].str.contains('\(continuing\)', regex=True, na=False)

In [95]:
yearly_report = scrap_yearly_report()
yearly_report = clean_yearly_report()
yearly_report

Found 44 ongoing eruptions

,volcano_name,country,eruption start date,eruption stop date,status,max vei
0,Purace,Colombia,2025 Jan 19,2025 Feb 21,Over,–
1,Lewotolok,Indonesia,2025 Jan 16,2025 Feb 21,On going,–
2,Telica,Nicaragua,2025 Jan 11,2025 Feb 21,On going,–
3,Poas,Costa Rica,2025 Jan 5,2025 Feb 21,On going,–
4,Bezymianny,Russia,2024 Dec 24,2025 Feb 21,On going,–
5,Kilauea,United States,2024 Dec 23,2025 Feb 21,On going,–
6,Dieng Volcanic Complex,Indonesia,2024 Dec 18,2025 Jan 6,Over,–
7,Home Reef,Tonga,2024 Dec 4,2025 Feb 21,On going,–
8,Dempo,Indonesia,2024 Nov 23,2025 Feb 21,On going,–
9,Kanlaon,Philippines,2024 Oct 19,2025 Feb 21,On going,–
10,Ahyi,United States,2024 Aug 5,2025 Feb 21,On going,–
11,Whakaari/White Island,New Zealand,2024 May 24,2025 Feb 21,On going,–
12,Taal,Philippines,2024 Apr 12,2025 Feb 21,On going,–
13,Lewotobi,Indonesia,2023 Dec 23,2025 Feb 21,On going,2
14,Marapi,Indonesia,2023 Dec 3,2025 Feb 21,On going,2
15,Etna,Italy,2022 Nov 27,2025 Feb 21,On going,2
16,Great Sitkin,United States,2021 May 25,2025 Feb 21,On going,2
17,Merapi,Indonesia,2020 Dec 31,2025 Feb 21,On going,1
18,Sangay,Ecuador,2019 Mar 26,2025 Feb 21,On going,2
19,Manam,Papua New Guinea,2018 May 10 ± 10 days,2025 Feb 21,On going,4
20,Nyamulagira,DR Congo,2018 Apr 14,2025 Feb 21,On going,0
21,Semeru,Indonesia,2017 Jun 6,2025 Feb 21,On going,4
22,Ol Doinyo Lengai,Tanzania,2017 Apr 9,2025 Feb 6,On going,0
23,Aira,Japan,2017 Mar 25,2025 Feb 21,On going,2
24,Sabancaya,Peru,2016 Nov 6,2025 Feb 21,On going,3
25,Langila,Papua New Guinea,2015 Oct 22 (?),2025 Feb 1,On going,2
26,Masaya,Nicaragua,2015 Oct 3,2025 Feb 6,On going,1
27,Tofua,Tonga,2015 Oct 2,2025 Feb 20,On going,0
28,Villarrica,Chile,2014 Dec 2 ± 7 days,2025 Feb 21,On going,3
29,Nevado del Ruiz,Colombia,2014 Nov 18,2025 Feb 21,On going,2
30,Saunders,United Kingdom,2014 Nov 12,2025 Jan 16,On going,1
31,Heard,Australia,2012 Sep 5 ± 4 days,2025 Feb 13,On going,0
32,Reventador,Ecuador,2008 Jul 27,2025 Feb 21,On going,2
33,Ibu,Indonesia,2008 Apr 5,2025 Feb 21,On going,1
34,Popocatepetl,Mexico,2005 Jan 9,2025 Feb 21,On going,2
35,Suwanosejima,Japan,2004 Oct 23,2025 Feb 21,On going,2
36,Nyiragongo,DR Congo,2002 May 17 (?),2025 Feb 21,On going,2
37,Fuego,Guatemala,2002 Jan 4,2025 Feb 21,On going,3
38,Bagana,Papua New Guinea,2000 Feb 28 (in or before),2025 Jan 31,On going,2
39,Sheveluch,Russia,1999 Aug 15,2025 Feb 21,On going,4
40,Erebus,Antarctica,1972 Dec 16 (in or before) ± 15 days,2025 Feb 21,On going,2
41,Erta Ale,Ethiopia,1967 Jul 2 (in or before) ± 182 days,2025 Feb 21,On going,0
42,Stromboli,Italy,1934 Feb 2,2025 Feb 21,On going,2
43,Dukono,Indonesia,1933 Aug 13,2025 Feb 21,On going,3
44,Santa Maria,Guatemala,1922 Jun 22,2025 Feb 21,On going,3
45,Yasur,Vanuatu,1270 ± 110 years,2025 Feb 21,On going,3